antora:
  extensions:
    - '@antora/collector-extension'
    - id: '@antora/atlas-extension'
      require: '@antora/atlas-extension'
      enabled: false
    - '@today-tech/antora-extensions/latest-version-extension'
    - require: '@today-tech/antora-extensions/root-component-extension'
      root_component_name: 'framework'
site:
  title: Polaris ORM 文档手册
content:
  sources:
    - url: ./..
      branches: HEAD
      start_path: polaris-docs
      worktrees: true
asciidoc:
  attributes:
    page-stackoverflow-url: https://stackoverflow.com/questions/tagged/polaris-orm
    hide-uri-scheme: '@'
    page-pagination: ''
    primary-site-url: https://docs.polaris-orm.cn
    tabs-sync-option: '@'
  extensions:
    - '@asciidoctor/tabs'
  sourcemap: true
urls:
  latest_version_segment: ''
  redirect_facility: httpd
runtime:
  cache_dir: ./build/.cache/antora
  log:
    failure_level: warn
ui:
  bundle:
    url: https://github.com/today-tech/antora-ui/releases/download/latest/ui-bundle.zip?v=2
    snapshot: true
